export const MAIN_ROUTE = '/'
export const TEAM_ROUTE = '/team'
export const TEAMS_ROUTE = '/teams'
export const USER_ROUTE = '/user'
export const USERS_ROUTE = '/users'
export const LOGIN_ROUTE = '/login'
export const SIGNUP_ROUTE = '/signup'
export const PROFILE_ROUTE = '/profile'
